config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "about", to: "pages#about"
  get "home", to: "pages#home"
  resources :projects, only: [:index, :show, :create, :new, :edit, :update, :destroy] do
    collection do
      patch :sort
    end
    resources :canvases, only: [:new, :create]
  end

  resources :canvases, only: [:edit, :show, :update, :destroy] do
    member do
      patch :update_notes
      patch :update_name
      patch :update_photo
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/canvas.rb
class Canvas < ApplicationRecord
  belongs_to :project
  mount_uploader :photo, PhotoUploader
  before_validation :set_default_name
  validates :name, uniqueness: { scope: :project_id,
    message: "should be unique for the given project" }


private
    def set_default_name
      if name.nil?
        time = Time.now.strftime '%Y-%m-%d%H:%M:%S'
        self.name = Project.find(project_id).name + "_" + time.to_s
      end
    end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :canvases, dependent: :delete_all
  mount_uploader :image, ImageUploader
  validates :name, uniqueness: { scope: :user_id,
    message: "should be unique for the given user" }
  validates :date, format: { with: /(|(0[1-9])|(1[0-2]))((0[1-9])|(1\d)|(2\d)|(3[0-1]))((\d{2}))/,
    message: "only format 'mmddYY' allowed" }, length: { maximum: 6 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects, dependent: :destroy
  has_many :canvases, through: :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    projects_path
  end

  def after_sign_up_path_for(resource)
    projects_path
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:fname, :lname])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fname, :lname])
  end

  # Pundit staff

  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  # end of Pundit staff
end

app/controllers/canvases_controller.rb
class CanvasesController < ApplicationController

  before_action :find_canvas, only: [:show, :edit, :update, :update_notes, :update_name, :update_photo, :destroy]

  def new
    @canvas = Canvas.new
    authorize @canvas
    @project = Project.find(params[:project_id])
  end

  def create
    @canvas = Canvas.new(canvas_params)
    authorize @canvas
    @canvas.project = Project.find(params[:project_id])
    @canvas.save
    redirect_to(edit_canvas_path(@canvas), :notice => 'Canvas saved.')
  end

  def edit
    authorize @canvas
    @project = Project.find(@canvas.project_id)
  end

  def update
    authorize @canvas
      @canvas.state_json = params[:canvas][:state_json]
      @canvas.canvas_svg = params[:canvas][:canvas_svg]
      @canvas.save
  end

  def update_notes
    authorize @canvas
      @canvas.notes = params[:canvas][:notes]
      if @canvas.save
        respond_to do |format|
          format.html { redirect_to edit_canvas_path(@canvas) }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'canvases/show' }
          format.js
        end
      end
  end

  def update_name
    authorize @canvas
    @canvas.name = params[:canvas][:name]
    if @canvas.save
      redirect_to canvas_path(@canvas)
    else
      @canvas.name = ""
      render :show
    end
  end

  def update_photo
    authorize @canvas
    @canvas.photo = params[:canvas][:photo]
    @canvas.save
    redirect_to canvas_path(@canvas)
  end

  def show
    authorize @canvas
  end

  def destroy
    authorize @canvas
    @project = Project.find(@canvas.project_id)
    Canvas.destroy(params[:id])
    render "projects/show"
  end

  private

  def find_canvas
    @canvas = Canvas.find(params[:id])
  end

  def canvas_params
    params.require(:canvas).permit(:state_json, :canvas_svg, :project, :notes, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
  end

  def about
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  # skip_before_action :verify_authenticity_token, only: [:sort]

  def index
    @projects = policy_scope(Project.order(:position))
  end

  def sort
    params[:order].each do |index, id|
      @project = Project.find(id)
      authorize @project
      @project.position = index
      @project.save
    end
    @projects = Project.where(user: current_user).order(:position)
    respond_to do |format|
      format.js {render json: @projects}
      # format.html {redirect_to projects_path}
    end
    # render formats: :js, handlers: :erb
  end

  def show
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    authorize @project
  end

  def update
    authorize @project
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    authorize @project
    redirect_to projects_path if @project.destroy!
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :date, :location, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/canvases/_note.html.erb
 <p><%= simple_format(canvas.notes) %></p>

app/views/canvases/_note_form.html.erb
<%= simple_form_for(canvas, url: update_notes_canvas_url(canvas), remote: true, method: :patch) do |form| %>

  <%= form.input :notes, as: :text, label: false, input_html: { value: canvas.notes, style: 'min-height: 75px;'} %>
 <div class="text-right mb-3">
  <%= form.button :submit, 'Save', class: "btn_white_show_normal" %>
</div>

<% end %>

app/views/canvases/edit.html.erb
<div class="cont">
  <div class="row justify-content-center pt-4">
<%
=begin%>
 
    <div class="top-side-navigation col-2"> <%= @canvas.name.nil? ? "Title" : @canvas.name %></div>
    <div class="top-navigation col-10">
      <%= link_to  '<i class="fas fa-times"></i>'.html_safe, project_path(@canvas), class: 'crud-btn d-inline float-right' %>
      <%= form_for :canvas, url: canvas_url(@canvas), method: :patch, html: { id: "save-btn" } do |f|%>
        <%= f.hidden_field :state_json, id: 'canvas_json' %>
        <%= f.hidden_field :canvas_svg, id: 'canvas_svg' %>
        <%= f.button '<i class="far fa-save"></i>'.html_safe, id: 'save-submit', class: 'crud-btn d-inline float-right' %>
      <% end %>
    </div> 
<%
=end%>
    <div class="side-navigation col-2">
      <div class="nav_btn"><p id="equip">Subject Position</p>
      </div>
      <div class="nav_btn drop"><p>Camera</p>
        <ul class="drop-content">
          <li id="equip">35 mm</li>
          <li id="equip">Medium format</li>
          <li id="equip">View camera</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Light</p>
        <ul class="drop-content">
          <li id="equip" type="Strobe">Strobe</li>
          <li id="equip">Standart reflector</li>
          <li id="equip">Umbrella</li>
          <li id="equip">Softbox</li>
          <li id="equip">Beauty dish</li>
          <li id="equip">Med reflector</li>
          <li id="equip">Long reflectore</li>
          <li id="equip">XL umbrella</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Grip</p>
        <ul class="drop-content">
          <li id="equip">Large boom</li>
          <li id="equip">Frame</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Reflectors</p>
        <ul class="drop-content">
          <li id="equip">Black V Flat</li>
          <li id="equip">White V Flat</li>
          <li id="equip">V Flat Open</li>
          <li id="equip">Silver reflector</li>
          <li id="equip">White reflector</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Misc</p>
        <ul class="drop-content">
          <li id="equip">Cube</li>
          <li id="equip">Work light</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Environment</p>
        <ul class="drop-content">
          <li id="equip">Seamless paper</li>
          <li id="equip">Wall</li>
          <li id="equip">Window</li>
        </ul>
      </div>
      <div id="text-btn" class="nav_btn"><p>Text</p></div>
      <div id="drawing-mode-btn" class="nav_btn"><p>Drawing mode</p></div>
      <button id="delete-btn" class="nav_btn"><p>Delete item</p></button>
      <%= link_to project_path(@project), class: 'nav-btn' do %>
        <div class="nav_btn"><p><i class="fas fa-chevron-left"></i>  Project page</p></div>
      <% end %>
      <div class="nav_btn"><p></p></div>
      <%= form_for :canvas, url: canvas_url(@canvas), method: :patch, html: { id: "save-btn" } do |f|%>
        <%= f.hidden_field :state_json, id: 'canvas_json' %>
        <%= f.hidden_field :canvas_svg, id: 'canvas_svg' %>
        <%= f.button 'Save', id: 'save-submit', class: "nav_btn" %>
      <% end %>
    </div>
    <div class="canvas-cont col-10">
      <canvas id="canvas" width="1000px" height="600px" data-canvas-json="<%= @canvas.state_json %>" ></canvas>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'canvas' %>

app/views/canvases/new.html.erb
<div class="cont">
  <div class="row justify-content-center pt-4">
<%
=begin%>
 
    <div class="top-side-navigation col-2"> <%= @canvas.name.nil? ? "Title" : @canvas.name %></div>
    <div class="top-navigation col-10">
      <%= link_to  '<i class="fas fa-times"></i>'.html_safe, project_path(@canvas), class: 'crud-btn d-inline float-right' %>
      <%= form_for :canvas, url: project_canvas_url(@canvas), method: :patch, html: { id: "save-btn" } do |f|%>
        <%= f.hidden_field :state_json, id: 'canvas_json' %>
        <%= f.hidden_field :canvas_svg, id: 'canvas_svg' %>
        <%= f.button '<i class="far fa-save"></i>'.html_safe, id: 'save-submit', class: 'crud-btn d-inline float-right' %>
      <% end %>
    </div> 
<%
=end%>
    <div class="side-navigation col-2">
      <div class="nav_btn"><p id="equip">Subject Position</p>
      </div>
      <div class="nav_btn drop"><p>Camera</p>
        <ul class="drop-content">
          <li id="equip">35 mm</li>
          <li id="equip">Medium format</li>
          <li id="equip">View camera</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Light</p>
        <ul class="drop-content">
          <li id="equip" type="Strobe">Strobe</li>
          <li id="equip">Standart reflector</li>
          <li id="equip">Umbrella</li>
          <li id="equip">Softbox</li>
          <li id="equip">Beauty dish</li>
          <li id="equip">Med reflector</li>
          <li id="equip">Long reflectore</li>
          <li id="equip">XL umbrella</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Grip</p>
        <ul class="drop-content">
          <li id="equip">Large boom</li>
          <li id="equip">Frame</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Reflectors</p>
        <ul class="drop-content">
          <li id="equip">Black V Flat</li>
          <li id="equip">White V Flat</li>
          <li id="equip">V Flat Open</li>
          <li id="equip">Silver reflector</li>
          <li id="equip">White reflector</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Misc</p>
        <ul class="drop-content">
          <li id="equip">Cube</li>
          <li id="equip">Work light</li>
        </ul>
      </div>
      <div class="nav_btn drop"><p>Environment</p>
        <ul class="drop-content">
          <li id="equip">Seamless paper</li>
          <li id="equip">Wall</li>
          <li id="equip">Window</li>
        </ul>
      </div>
           <div id="text-btn" class="nav_btn"><p>Text</p></div>
      <div id="drawing-mode-btn" class="nav_btn"><p>Drawing mode</p></div>
      <button id="delete-btn" class="nav_btn"><p>Delete item</p></button>
      <%= link_to project_path(@project), class: 'nav-btn' do %>
        <div class="nav_btn"><p><i class="fas fa-chevron-left"></i>  Project page</p></div>
      <% end %>
      <div class="nav_btn"><p></p></div>
      <%= form_for :canvas, url: project_canvases_url, method: :post, html: { id: "save-btn" } do |f|%>
        <%= f.hidden_field :state_json, id: 'canvas_json' %>
        <%= f.hidden_field :canvas_svg, id: 'canvas_svg' %>
        <%= f.button 'Save', id: 'save-submit', class: "nav_btn" %>
      <% end %>
    </div>
    <div class="canvas-container col-10">
      <canvas id="canvas" width="1000px" height="600px" data-canvas="<% @canvas %>"></canvas>
    </div>
    <div class="bottom-navigation" id="bottom-navigation"></div>
  </div>
</div>
<%= javascript_pack_tag 'canvas' %>

app/views/canvases/show.html.erb
<div class='container-for-canvases-show'>
  <div class="row canvas-show-all-b justify-content-center">

    <div class="col-3 btn-menu">

      <% if @canvas.name.nil? %>
        <p class="btn_white_show" id="add-canvas-title">Add title</p>
      <% else %>
        <p class="btn_white_show" id="add-canvas-title">Update title</p>
      <% end %>
      <div class="title-form d-none">
        <%= simple_form_for(@canvas, url: update_name_canvas_url) do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, label: false %>
        <%= f.button :submit, 'Save', class: 'btn canvas-save-btn'  %>
        <% end %>
      </div>

      <%= link_to edit_canvas_path(@canvas), id: "btn_edit_canvas" do %>
        <p class= "btn_white_show">Edit Canvas</p>
      <% end %>
      <% if @canvas.notes.nil? %>
        <p class="btn_white_show" id="btn_add_notes">Add notes</p>
      <% else %>
        <p class="btn_white_show" id="btn_add_notes">Update notes</p>
      <% end %>

      <% if @canvas.photo.url.nil?  %>
        <p class="btn_white_show" id="add-canvas-photo">Add image</p>
      <% else %>
        <p class="btn_white_show" id="add-canvas-photo">Update image</p>
      <% end %>
      <div class="photo-form d-none">
        <%= simple_form_for(@canvas, url: update_photo_canvas_url) do |f| %>

          <%= image_tag "", class: "hide photo-preview-size", id: "photo-preview" %>
          <%= f.input :photo, input_html: { class: 'hide', id: 'photo-input'}, label_html: { class: 'upload-photo canvas-upload-photo'}, label: 'Upload a photo' %>
          <%= f.button :submit, 'Save', class: 'btn canvas-save-btn'  %>
        <% end %>
      </div>
      <%= link_to project_path(@canvas.project) do %>
        <p class= "btn_white_show">Back to project</p>
      <% end %>

  </div>

    <div class="row col-9 d-flex justify-content-around ">
      <% if !@canvas.photo.url.nil?  %>
        <%= cl_image_tag @canvas.photo, class: "obj-fit-cvr canvas-photo" %>
      <% else %>
        <div class="obj-fit-cvr canvas-photo"></div>
      <% end %>
      <div class="background-grey-flex">
        <div id="render-svg" data-canvas-svg="<%= @canvas.canvas_svg %>" ></div>
      </div>
    </div>

  </div>

  <div class="canvas-name">
    <h6><%= @canvas.name %></h6>
  </div>



  <div class="canvas-notes-container">
     <%= render 'canvases/note', canvas: @canvas %>
  </div>
</div>


<script>
let button = document.getElementById("btn_add_notes");
  button.addEventListener("click", () => {

    let notesDiv = document.querySelector(".canvas-notes-container");
    notesDiv.innerHTML = "<%= j render 'canvases/note_form', canvas: @canvas %>"
  })
</script>
<%= javascript_pack_tag 'toggle-show-canvas' %>
<%= javascript_pack_tag 'canvas-show' %>

app/views/canvases/update_notes.js.erb
var notesDiv = document.querySelector(".canvas-notes-container");
notesDiv.innerHTML = "<%= j render 'canvases/note', canvas: @canvas %>";

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>LITE-IT - make shooting easy</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('logo.png') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/about.html.erb
 <!--  <div class="center"> -->
   <!--  <div class="crud-box"> -->
      <div class=" crud-box about">
      <p><span style="font-weight:bold;">LITE-IT</span> is an application made for photographers who are looking to record their studio set-ups for personal reference and to share with their teams.</p>
      </div>
  <!--   </div> -->
 <!--  </div> -->

app/views/pages/home.html.erb
<div class="home-logo">

  <div class="home-only" href="#">
    <p class="main-intro">make shooting easy</p>
    <div class="logo-full">
    <p class="logo-main">LITE-IT</p>
    <div class="inner">
      <p></p>
      </div>
    </div>
  </div>
  </div>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs form-labels form-box">
    <%= f.input :name, label: "Project Name" %>
    <%= f.input :date, label: "Date", placeholder: "mmddyy" %>
    <%= f.input :location, label: "Location" %>
    <div id="image-container">
      <%= image_tag "", class: "hide", id: "photo-preview" %>
    </div>
    <%= f.input :image, input_html: { class: 'hide', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: 'Upload a photo' %>

  </div>

  <div class="form-actions btn-white">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_index-partial.html.erb
<% projects.each_with_index do |project, index| %>
  <li class="list-unstyled" id="<%= project.id %>">
    <%= link_to project_path(project), class: "card-link", id: dom_id(project) do  %>
      <div class="project-card <%= 'project-card-left' if index.odd? %>">
        <div class="project-title <%=  index.odd? ? 'project-title-left' :'project-title-rt' %> " >
          <%= project.name %>
        </div>
          <div class="img">
          <% if project.image %>
              <%= cl_image_tag project.image %>
          <% end %>
        </div>
      </div>
    <% end %>
  </li>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
  <div class="center">
    <div class="crud-box">

      <%= render 'form', project: @project %>

    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="dashboard-container">
  <% if @projects.empty? %>
    <div class="waiting">
      <h4>Waiting for your first project!</h4>
    </div>

  <% else %>
    <ul id="projects">
      <%= render 'projects/index-partial', projects: @projects %>
    </ul>
  <% end %>
</div>


<%= content_for(:after_js) do  %>
<%= javascript_pack_tag("sorting") %>
<% end %>

app/views/projects/new.html.erb
  <div class="row">
    <div class="center">
      <div class="crud-box">

      <%= render 'form', project: @project %>

      </div>
    </div>
  </div>

app/views/projects/show.html.erb
<div class="black">
<div class="d-flex">
  <div class="prj-btns-canvas-descr">
     <div class="container justify-content-md-center">
        <div class="row">
          <div class="col-12 col-md-4 m-0">
            <div class="prj-descr">
              <h2><%= @project.name %></h2>
              <h5><%= @project.location %></h5>
            </div>
            <div class="edit-delete-project">
            <span>
              <%= link_to "Edit Project", edit_project_path %>
               /
              <%= link_to "Delete Project", project_path, method: 'delete', data: { confirm: "Do you want to delete this project ?"} %>
              </span>
            </div>
          </div>
        </div>
        <div class="row canvases-container">
            <div class="col-4" class="card-canvas">
              <%= link_to new_project_canvas_path(@project) do %>
              <div id="add-canvas" class="card-canvas tooltip-new-canvas">
                <%= image_tag "https://res.cloudinary.com/dkjjz54zd/image/upload/v1569397112/_version_b_zf3y7q.png", alt: "Add new canvas", width: 335, height: 185 %>
                <span class="tooltiptext">Create new canvas</span>
              </div>
              <% end %>
            </div>

          <% @project.canvases.each_with_index do |canvas, index| %>
          <div class="col-md-4 card-container">

            <%= link_to canvas_path(canvas), id: "link" do %>

                <% if !canvas.photo.url.nil? %>
                  <div class="card-canvas">
                    <div  class="face" id='upside'>
                    <%= cl_image_tag canvas.photo, height: 182, crop: :fill %>
                    </div>
                    <div class="face" id='downside'>
                      <div id="render-svg" data-canvas-svg="<%= canvas.canvas_svg %>" style="background: white;">
                      </div>
                    </div>
                  </div>
                <% else %>
                  <div id="render-svg" data-canvas-svg="<%= canvas.canvas_svg %>" style="background: white;"></div>
                <% end #end of if/else %>
          <% end #end of link %>
            <div class="controls">
              <i data-link="<%= 'lite-it.herokuapp.com' + canvas_path(canvas) %>" class="fas fa-link tooltip">
              <span class="tooltiptext">Copy link to clipboard</span></i>
              <%= link_to  '<i class="fas fa-pen-square"></i>'.html_safe, edit_canvas_url(canvas) %>
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, canvas_path(canvas), method: 'delete', data: { confirm: "Do you want to delete this canvas?"} %>
            </div>
          </div>
        <% end #end of each with %>
       </div>
     </div>
  </div>
</div>
</div>
<%= javascript_pack_tag 'canvas-show' %>

app/views/projects/sort.js.erb
var list = document.querySelector('#projects');
list.innerHTML = "<%= j render 'projects/index-partial', projects: @projects %>"

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-container">

    <% if user_signed_in? %>
    <%= link_to "LITE-IT", root_path, class: "btn-navbar__logged-in logo" %>

    <% if current_user.fname.empty? %>

    <p class="panel-navbar__logged-in" >Welcome</p>
    <% else %>
    <p class="panel-navbar__logged-in">Welcome, <%=  current_user.fname %></p>
    <% end %>

    <%#= link_to "Welcome, #{current_user.fname}", "#", class: "btn-navbar__logged-in" %>


    <% if !@project.nil? && !@project.id.nil? %>
    <%= link_to "Edit", edit_project_path(@project), class: "btn-navbar__logged-in" %>
    <% else %>
    <%= link_to "Create", new_project_path, class: "btn-navbar__logged-in" %>
    <% end %>
    <%= link_to "Browse", projects_path, class: "btn-navbar__logged-in" %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn-navbar__logged-in" %>
    <% else %>
        <%= link_to "LITE-IT", "#", class: "btn__navbar logo" %>
        <%#= link_to "Hide me", "#", class: "btn__navbar", style: "color:white" %>
        <p class="panel__navbar", style="color:white">Unknown user</p>
        <% if params[:action] == "about" %>
          <%= link_to "About", root_path, class: "btn__navbar" %>
        <% else %>
          <%= link_to "About", about_path, class: "btn__navbar" %>
        <% end %>
        <%= link_to "Log in", new_user_session_path, class: "btn__navbar" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn__navbar" %>
    <% end %>

</div>